### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by enuenan** [fahad1226/lara-dep#2]
Just cloned your repo and I've got issue while migrating the database. 

![image](https://user-images.githubusercontent.com/30136410/195964816-1a5e4f8a-b9b0-4175-bfc7-c03f110d99f1.png)

**Comment by fahad1226** [comment]
Thanks for letting me know, I will fix them in no time.

**Comment by fahad1226** [comment]
@enuenan the issue has been solved, you could check them now.
also, I have added 2 new lessons to the repo.
thanks for giving me feedback.
